// web-app-nuxt/components/display/DisplayProjects.vue
<template>
  <div class="mx-auto py-20 w-2/3 flex flex-col gap-y-10">
    <h1 class="text-4xl font-bold text-center">Projects</h1>
  
    <h2 class="text-2xl font-bold text-center">Projects that I currently work on</h2>

    <ul class="list-disc">
      <h3 class="text-xl font-bold">Github</h3>
      <div class="py-4">
        <li>
          <a 
            href="https://github.com/theplanetv/planetv-website"
            class="text-blue-500 underline"
          >
            PlanetV website
          </a>
        </li>
      </div>
    </ul>
  </div>
</template>

// web-next-ts/src/components/DisplayProjects.tsx
import H1 from "@/components/H1";
import H2 from "@/components/H2";

export default function DisplayProjects(): JSX.Element {
  return (
    <div className="mx-auto py-20 w-fit flex flex-col gap-y-10">
      <H1>Projects I work on</H1>

      <ul className="flex flex-col gap-y-5 list-disc">
        <H2>Open source projects</H2>

        <div>
          <li><a className="underline" href="https://github.com/theplanetv/planetv-website">PlanetV Website</a></li>
          <li><a className="underline" href="https://github.com/BambooEngine/ibus-bamboo">ibus-bamboo</a></li>
        </div>
      </ul>
    </div>
  )
}
